# Generated by Django 3.1.2 on 2021-03-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_media', '0003_auto_20210311_1940'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_image_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_media.profileavatarimage', verbose_name='user profile avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
