# Generated by Django 3.1.2 on 2021-02-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image_file', models.ImageField(upload_to='post_images/', verbose_name='Картинка для поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.post', verbose_name='Пост')),
            ],
        ),
    ]
