# Generated by Django 3.1.2 on 2021-03-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20210311_1926'),
        ('app_media', '0002_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'post image', 'verbose_name_plural': 'post images'},
        ),
        migrations.AlterModelOptions(
            name='profileavatarimage',
            options={'verbose_name': 'profile avatar image', 'verbose_name_plural': 'profile avatar images'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_image_file',
            field=models.ImageField(upload_to='post_images/', verbose_name='Image for post'),
        ),
        migrations.AlterField(
            model_name='profileavatarimage',
            name='avatar_image_file',
            field=models.ImageField(upload_to='avatar_images/', verbose_name='picture, user profile avatar'),
        ),
    ]
