# Generated by Django 3.1.2 on 2021-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(verbose_name='Дата публикации поста'),
        ),
    ]
